#!/usr/bin/bash

# ------------------------------
# An idempotent config file to be sourced in a bash session

# alias definitions
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias rm='rm -i'

# Load environment last (and only load once per session)
if [[ $BASH_ENV_LOADED != 1 ]]; then
    echo "---  Loading bash env"
    export BASH_ENV_LOADED=1

    if [[ -f $HOME/.bash_environment ]]; then
        source $HOME/.bash_environment
    else
        echo "warning: environment file missing ($HOME/.bash_environment)"
    fi

    # init pyenv if necessary
    if command -v pyenv 1>/dev/null 2>&1; then
        eval "$(pyenv init -)"
    fi

    # init poetry if necessary
    if [[ -f $HOME/.poetry/env ]]; then
        source $HOME/.poetry/env
    fi

    echo "===> Loaded bash env"
fi
