#!/bin/bash

# ------------------------------
# User bash environment configuration


# ..............................
# Non-idempotent configuration (execute once per environment)
if [[ ${BASH_ENV_LOADED} -eq 0 ]]; then
    export BASH_ENV_LOADED=$(( 1 ))

    # >> bank the vanilla path for convenience (now hard coded for reliability)

    # NOTE: this is fallback if things get weird
    # export default_path="${PATH}"

    # These are based on what looks reasonable in my existing path
    unix_paths="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    export default_path="${unix_paths}"

    # If we don't have terminfo built, use xterm
    if [[ $(find "${HOME}/.terminfo" -name '*alacritty*' | wc -l) -eq 2 ]]; then
        export TERMINAL=alacritty

    else
        export TERMINAL=xterm-256color

    fi
fi


# ..............................
# Idempotent configuration (may be executed many times)

export GIT_EDITOR=vim
export EDITOR=vim
export PAGER=less

# Signal that this file was invoked
echo "===> Loaded bash environment"
